spring:
  application:
    name: java-mall-coupon
  cloud:
    nacos:
      discovery:
        server-addr: 82.157.130.123:8848
      config:
        server-addr: 82.157.130.123:8848
        group: DEFAULT_GROUP
        namespace: 87d9a131-4d65-49ae-91b2-c7951677b737
  config:
    import:
      - optional:nacos:test.yml?refreshEnabled=false
      - optional:nacos:database.yml?refreshEnabled=true

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 20001
logging:
  level:
    org.epha.mall: debug
