spring:
  application:
    name: mall-auth
  cloud:
    nacos:
      discovery:
        server-addr: 82.157.130.123:8848
      config:
        server-addr: 82.157.130.123:8848
        group: DEFAULT_GROUP
        namespace: cf3a5ad5-d0d7-4cd0-bd17-c3dab5fba0da
  config:
    import:
      - optional:nacos:test.yml?refreshEnabled=false
      - optional:nacos:redis.yml?refreshEnabled=true

server:
  port: 30002

