spring:
  application:
    name: mall-auth

# nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 82.157.130.123:8848
      config:
        server-addr: 82.157.130.123:8848
        group: DEFAULT_GROUP
        namespace: cf3a5ad5-d0d7-4cd0-bd17-c3dab5fba0da
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  config:
    import:
      - optional:nacos:test.yml?refreshEnabled=false

# spring session redis配置
  session:
    store-type: redis

# redis配置
  redis:
    host: localhost
    port: 6379


server:
  port: 30001
  servlet:
    session:
      timeout: 30m

#线程池配置
jmall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

logging:
  level:
    org.epha.mall.auth.controller: debug

management:
  endpoints:
    web:
      exposure:
        include: *

