spring:
  application:
    name: java-mall-ware
  cloud:
    nacos:
      discovery:
        server-addr: 82.157.130.123:8848
      config:
        server-addr: 82.157.130.123:8848
        group: DEFAULT_GROUP
        namespace: 3050abd8-2aab-40c9-916d-153ca3ce09cb
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  config:
    import:
      - optional:nacos:test.yml?refreshEnabled=false
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/jmall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    # 消息抵达Broker自动回调
    publisher-confirm-type: correlated
    # 消息未正确抵达Queue触发回调
    publisher-returns: true
    # 以异步方式快速触发returnsConfirm回调
    template:
      mandatory: true
    # 设置消费端手动ACK
    listener:
      simple:
        acknowledge-mode: manual

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 30011
logging:
  level:
    org.epha.mall.ware: debug

management:
  endpoints:
    web:
      exposure:
        include: *

