spring:
  application:
    name: java-mall-ware
  cloud:
    nacos:
      discovery:
        server-addr: 82.157.130.123:8848
      config:
        server-addr: 82.157.130.123:8848
        group: DEFAULT_GROUP
        namespace: 3050abd8-2aab-40c9-916d-153ca3ce09cb
  config:
    import:
      - optional:nacos:test.yml?refreshEnabled=false
      - optional:nacos:database.yml?refreshEnabled=true
      - optional:nacos:rabbitmq.yml?refreshEnabled=true

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 20005
logging:
  level:
    org.epha.mall.ware: debug

