spring:
  application:
    name: java-mall-elasticsearch
  cloud:
    nacos:
      discovery:
        server-addr: 82.157.130.123:8848
      config:
        server-addr: 82.157.130.123:8848
        group: DEFAULT_GROUP
        namespace: 9a5a99a5-b7b1-45dc-8ba5-d9b3518cadd5
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  config:
    import:
      - optional:nacos:test.yml?refreshEnabled=false

  # zipkin配置
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web # 使用http传输数据
  sleuth:
    sampler:
      probability: 1 # 采样频率设置为100%，默认为0.1 10%

server:
  port: 30004
logging:
  level:
    org.epha.mall: debug

elasticsearch:
  connection:
    host: localhost
    port: 9200
    protocol: http
  auth:
    username: elastic
    password: V+H8B-qkCg1cv2QRL=1F

management:
  endpoints:
    web:
      exposure:
        include: *
