spring:
  application:
    name: java-mall-product
  cloud:
    nacos:
      discovery:
        server-addr: 82.157.130.123:8848
      config:
        server-addr: 82.157.130.123:8848
        group: DEFAULT_GROUP
        namespace: c0f5caa0-730b-41f7-b3b3-d738801cdb1a
  config:
    import:
      - optional:nacos:test.yml?refreshEnabled=false
      - optional:nacos:database.yml?refreshEnabled=true
      - optional:nacos:redis.yml?refreshEnabled=true
  cache:
    type: redis
    redis:
      time-to-live: 36000

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 20004

logging:
  level:
    org.epha.mall: debug

