spring:
  application:
    name: mall-third-party
  cloud:
    nacos:
      # nacos服务发现，默认都在public namespace下
      discovery:
        server-addr: 82.157.130.123:8848
      # nacos自动配置，每个服务有自己的namespace
      config:
        server-addr: 82.157.130.123:8848
        group: DEFAULT_GROUP
        namespace: 6cdda117-c0b7-4bd7-b829-1bee093859bb
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  config:
    import:
      - optional:nacos:test.yml?refreshEnabled=false
      - optional:nacos:oss.yml?refreshEnabled=true
      - optional:nacos:sms.yml?refreshEnabled=true
  # zipkin配置
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web # 使用http传输数据
  sleuth:
    sampler:
      probability: 1 # 采样频率设置为100%，默认为0.1 10%

server:
  port: 30010

management:
  endpoints:
    web:
      exposure:
        include: *
