spring:
  application:
    name: java-mall-order
  cloud:
    nacos:
      discovery:
        server-addr: 82.157.130.123:8848
      config:
        server-addr: 82.157.130.123:8848
        group: DEFAULT_GROUP
        namespace: 29ec7dca-205e-4933-bee3-884038de2fef
  config:
    import:
      - optional:nacos:test.yml?refreshEnabled=false
      - optional:nacos:database.yml?refreshEnabled=true


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 20003
