spring:
  application:
    name: java-mall-order
  cloud:
    nacos:
      discovery:
        server-addr: 82.157.130.123:8848
      config:
        server-addr: 82.157.130.123:8848
        group: DEFAULT_GROUP
        namespace: 29ec7dca-205e-4933-bee3-884038de2fef
  config:
    import:
      - optional:nacos:test.yml?refreshEnabled=false
      - optional:nacos:database.yml?refreshEnabled=true
      - optional:nacos:rabbitmq.yml?refreshEnabled=false
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379




mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

seata:
  tx-service-group: mygroup
  service:
    vgroup-mapping:
      mygroup: default


server:
  port: 20003

#线程池配置
jmall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

logging:
  level:
    org.epha.mall.order: debug
